### ISSUE TITLE
in-game error: combinator behavior error

### ISSUE THREAD

**Issue by anonhostpi** [anonhostpi/mk-fg-games#6]
![image](https://github.com/user-attachments/assets/7f571509-d1a3-43ad-b6af-2b3e05f74ef2)

> ```
> The mod Moon Logic (0.0.83) caused a non-recoverable error.
> Please report this error to the mod author.
> 
> Error while running event Moon_Logic::on_tick (ID 0)
> LuaConstantCombinatorControlBehavior doesn't contain key signals_count.
> stack traceback:
> 	[C]: in function '__index'
> 	__Moon_Logic__/control.lua:290: in function 'mlc_update_output'
> 	__Moon_Logic__/control.lua:338: in function 'mlc_update_code'
> 	__Moon_Logic__/control.lua:463: in function 'mlc_init'
> 	__Moon_Logic__/control.lua:798: in function <__Moon_Logic__/control.lua:792>
> ```

Trace (Corrected):
- https://github.com/anonhostpi/mk-fg-games/blob/0778c1a9e0dfae86f561c571d78629258541ac64/factorio/Moon_Logic/control.lua#L265

**Comment by mk-fg** [comment]
It was changed because apparently constant combinators now have "sections" (like tabs or something in UI?):
https://lua-api.factorio.com/latest/classes/LuaConstantCombinatorControlBehavior.html
These also have filters and multipliers, so presumably some kind of fancy new UI.

While they used to have just a flat array of signals:
https://lua-api.factorio.com/1.1.110/classes/LuaConstantCombinatorControlBehavior.html

There's still no "number of slots" property for sections, so suspect it's either always infinite (and there's no need for that n_max sanity-check now), or maybe you're supposed to query it from a prototype of that combinator (which this mod creates anyway, so can also use shared constant).

**Comment by chilla55** [comment]
signal outputting and receiving should work now

**Comment by anonhostpi** [comment]
@mk-fg do you concur with my code review on #7? Was I right about how your code was intended to work?

**Comment by mk-fg** [comment]
I think `if n > n_max then` check was indeed removed just below, so that n_max=1 value is probably left unused there.
Dunno about "output all signals" part - check in-game if it has infinite slots, or maybe that number is still fixed but just have to be queried elsewhere (e.g. via prototypes table).
